feature/getting-started : Add Akeneo getting started
php-etl/documentation pull request #10
Opened 2021-07-26 07:42 UTC by programgames

2021-07-27 07:04 UTC, sebprt commented on content/installation/getting-started-akeneo/_index.en.md
> +composer require php-etl/satellite php-etl/akeneo-expression-language php-etl/akeneo-plugin
Normalement Satellite require le plugin akeneo, tu n'as pas beosin de le require à nouveau

2021-07-27 07:07 UTC, sebprt commented on content/installation/getting-started-akeneo/_index.en.md
> +If u want to start from scratch , create a composer project using the following command
"u" 😄

2021-07-27 09:24 UTC, gplanchat commented on content/installation/getting-started-akeneo/_index.en.md
> +composer require php-etl/satellite php-etl/akeneo-expression-language php-etl/akeneo-plugin
Laissons-le dans la doc, ce require devrait disparaitre à l'avenir

2021-07-30 06:24 UTC, gplanchat requested changes

2021-07-30 06:24 UTC, gplanchat commented on content/installation/getting-started-akeneo/_index.en.md
> +If u want to start from scratch , create a composer project using the following command
```suggestion
If you want to start from scratch , create a composer project using the following command
```

2021-07-30 06:26 UTC, merged