Updated menu organization, added the rejection and state documentation
php-etl/documentation pull request #18
Opened 2021-10-12 15:34 UTC by sebprt

2021-10-15 14:48 UTC, XaBe20 commented on README.md
> +![alt Middleware](assets/logo.svg)
à remplacer par le fichier favicon.png qui est beaucoup plus petit et ne cassera pas la mise en forme

2021-10-18 07:03 UTC, sebprt commented on README.md
> +![alt Middleware](assets/logo.svg)
Fait.

2021-10-28 13:55 UTC, gplanchat requested changes

2021-10-28 13:55 UTC, gplanchat commented on content/feature/rejection/_index.en.md
> +## What is it ?
```suggestion
- [What is it for?](#what-is-it-for)
- [Installation](#installation)
- [Usage](#usage)
  - [With RabbitMQ](#basic-usage)

---

## What is it for?
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/services/_index.en.md
> +## What is it ?
```suggestion
- [What is it for?](#what-is-it-for)
- [Installation](#installation)
- [Usage](#usage)
  - [Defining your arguments](#defining-your-arguments)
  - [Making the service public](#making-the-service-public)
  - [Using method calls](#using-method-calls)
  - [Using a service as an argument](#using-a-service-as-an-argument)

---

## What is it for?
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/services/_index.en.md
> +  App\Class\Bar: ~
```suggestion
  App\Foo\Bar: ~
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/services/_index.en.md
> +  App\Class\Bar:
```suggestion
  App\Foo\Bar:
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/services/_index.en.md
> +In this example, the `App\Class\Bar` service will have 3 parameters that will be passed into the
```suggestion
In this example, the `App\Foo\Bar` service will have 3 parameters that will be passed into the 
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/services/_index.en.md
> +  App\Class\Bar:
```suggestion
  App\Foo\Bar:
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/services/_index.en.md
> +  App\Class\Bar:
```suggestion
  App\Foo\Bar:
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/services/_index.en.md
> +      - '@App\Class\Bar'
```suggestion
  App\Foo\Foo:
    arguments:
      - '@App\Foo\Bar'
```

2021-10-28 13:55 UTC, gplanchat commented on content/feature/state/_index.en.md
> +## What is it ?
```suggestion
- [What is it for?](#what-is-it-for)
- [Installation](#installation)
- [Usage](#usage)
    - [With RabbitMQ](#basic-usage)
    - [Using a service](#using-a-service)
---

## What is it for?
```

2021-10-28 13:55 UTC, gplanchat commented on content/getting-started/pipeline/_index.en.md
> +
```suggestion
- [What is it for?](#what-is-it-for)
- [Installation](#installation)
- [Basic Usage](#basic-usage)
- [Advanced Usage](#advanced-usage)
  - [Using expressions](#using-expressions)
  - [Using services](#using-services)
  - [Adding logger](#adding-logger)
  - [Adding rejection](#adding-rejection)
  - [Adding state](#adding-state)

---

> A pipeline is a series of processes, also called steps, that filter or transform data.
> The first process takes raw input data, uses it and then
> sends the results to the second process, and so on, ending with the final result produced by the last process in progress.

![Pipeline schema](pipeline.svg)

The different steps of our pipeline are `extract`, `transform` or `load` but the transformation step isn't mandatory.

> Tip : It's possible to use multiple transformation steps in a pipeline.

## What is it for?

```

2021-10-28 14:03 UTC, merged