Reorganize getting-started + added a new tab "Core Concepts"
php-etl/documentation pull request #24
Opened 2023-02-14 16:33 UTC by sebprt

2023-02-15 08:28 UTC, gplanchat requested changes
**💭 thought:** évitons les "simply", "easily", "only", etc.

2023-02-15 08:28 UTC, gplanchat commented on content/core-concept/satellite/_index.en.md
> +Chaque autoload doit être constitué des clés suivantes :
```suggestion
Every autoloading configuration shall be in the following format:
```

2023-02-15 08:28 UTC, gplanchat commented on content/core-concept/satellite/_index.en.md
> +The `repositories` option is optional and allow you to use directories that are hosted on other repositories than Packagist.
```suggestion
The `repositories` parameter is optional. It allows you to use repositories that are not hosted on packagist.org.
```

2023-02-15 08:28 UTC, gplanchat commented on content/core-concept/satellite/_index.en.md
> +- `type`: it allows to determine which authentication type is used to access your repo, see [Authentication principles](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#aut
**❔ question:** Tu es sûr que la phrase est au bon endroit ? Pour moi le type sert à indiquer si c'est un dossier, un repo git ou un repos composer. L'authentification est au chapitre suivant.‏

2023-02-15 08:28 UTC, gplanchat commented on content/core-concept/satellite/_index.en.md
> +The `auth` option is optional and allows you to use packages that are protected by your server.
```suggestion
The `auth` parameter is optional and allows you to use registries that are not public and accessed through an authentication.
```

2023-02-15 08:28 UTC, gplanchat commented on content/core-concept/satellite/_index.en.md
> +You will need to tell Composer how to authenticate to the server that hosts them.
```suggestion
The option is the way for you to tell composer how to authenticate to the registry server.
```

2023-02-15 08:28 UTC, gplanchat commented on content/core-concept/satellite/_index.en.md
> +> Notice : Actually, the only way to identify to a repository is to use tokens.
```suggestion
> Notice : Currently, the only way to identify to a repository is to use tokens. Support for other authentication methods is in our backlog.
```

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/environment-setup/_index.en.md
> +the application you must first have these 2 requirements.
```suggestion
Gyroscops is a command line application written in PHP. To be able to use the application, you will need to fulfill the following requirements:
```

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/environment-setup/_index.en.md
> +
```suggestion
### PHP 8.2 or higher
Before proceeding, make sure your computer has a PHP version higher than or equal to 8.2 installed.

For more information on how to install PHP, go to the [official documentation](https://www.php.net/manual/en/install.php).

```

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/environment-setup/_index.en.md
> +title: "Environment Setup"
**🔨 issue:** Il manque le cas où on build sous ‏Docker.

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/execution/_index.en.md
> +Once your PHP code is generated, you only need to execute it.
```suggestion
Once your PHP code is generated, it can be executed right away.
```

‏

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/execution/_index.en.md
> +However, depending on the adapter you have chosen in your configuration, the way to do it is different.
**💭 thought:** On ne devrait pas renvoyer sur la doc de ce qu'est un adapter ?‏

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/execution/_index.en.md
> +However, depending on the adapter you have chosen in your configuration, the way to do it is different.
```suggestion
In the following paragraphs, you will find the method for executing the satellites depending on the adapter you have chosen.
```

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/execution/_index.en.md
> +so please wait until the execution is completed.
**💭 thought:** La commande satellite a des commandes pour lancer les pipelines.

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/execution/_index.en.md
> +so please wait until the execution is completed.
```suggestion
This command will run your satellite service you have previously built as a Docker image you named `foo/satellite-name:latest`.
```

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/execution/_index.en.md
> +so please wait until the execution is completed.
**💭 thought:** est-ce qu'on n'en profiterait pas pour mettre des captures d'écran ?‏

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/installation/_index.en.md
> +In a terminal, type the following command:
```suggestion
Starting from here we will work inside a project directory we will name `my_project_directory`.
```

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/installation/_index.en.md
> +After creating your project, you will have to initialize your project and add all the dependencies you need.
```suggestion
Once the project dir is created and you have changed your current directory to it, the first task will be to initialize a composer project inside this directory and add all required dependencies.
```

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/installation/_index.en.md
> +> Notice: You must choose `dev` as the value for the `minimum-stability` option.
**🎯 suggestion:** proposes une commande `composer init` plus complète avec les options appropriées pour que l'utilisateur n'ait pas à chercher ce genre d'avertissement.‏

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/installation/_index.en.md
> +In the auto-generated `composer.json` file, add the following lines at the end :
**💭 thought:** il faudrait que l'on intègre ces changements dans la commande `satellite`‏

2023-02-15 08:28 UTC, gplanchat commented on content/getting-started/installation/_index.en.md
> +The most important thing you need to add to your project is our compiler :
```suggestion
Now, your environment is ready for the satellite compiler installation. The following command will install it.
```

2023-02-15 11:07 UTC, sebprt commented on content/core-concept/satellite/_index.en.md
> +- `type`: it allows to determine which authentication type is used to access your repo, see [Authentication principles](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#aut
Effectivement, c'est une erreur de ma part, je l'ai modifié

2023-02-15 11:10 UTC, sebprt commented on content/getting-started/environment-setup/_index.en.md
> +title: "Environment Setup"
Effectivement, je le rajoute

2023-02-15 13:54 UTC, sebprt commented on content/getting-started/execution/_index.en.md
> +However, depending on the adapter you have chosen in your configuration, the way to do it is different.
J'ai rajouté le lien

2023-02-15 14:27 UTC, sebprt commented on content/getting-started/execution/_index.en.md
> +so please wait until the execution is completed.
Effectivement, j'ai remplacé par `php bin/satellite run:pipeline build/`

2023-03-08 16:13 UTC, clemzarch commented on content/connectivity/csv/_index.en.md
>  If you want to see complete configurations, please go to the [examples](/examples) folder.
ca donne sur une 404.

2023-03-08 16:13 UTC, clemzarch commented on content/connectivity/csv/_index.en.md
> +    nonstandard: true
faut peut-etre montrer un exemple de config qui n'est activable qu'avec `nonstandard`

2023-03-08 16:13 UTC, clemzarch commented on content/core-concept/satellite/_index.en.md
> +The `require` parameter allows to add all the packages, write like `package_name:version`, that we need for your microservice.
```suggestion
The `require` parameter allows to add all the packages, written as `package_name:version`, that we need for your microservice.
```

et un coup on parle de "we", puis de "you" ?? qui écrit la config et qui a le microservice ?

2023-03-08 16:13 UTC, clemzarch commented on content/core-concept/satellite/_index.en.md
> +The `from_local` parameter is optional and copies local `composer.json`, `composer.lock` and `vendor` files in your
```suggestion
The `from_local` parameter is optional and copies local `composer.json`, `composer.lock` and `vendor` files into your 
```
pour faire comprendre qu'on le copie du local vers le microservice

2023-03-08 16:13 UTC, clemzarch commented on content/core-concept/satellite/_index.en.md
> +        - { name: 'private-packagist', type: 'composer', url: 'https://repo.packagist.com/package/' }
on peut les mettre dans l'ordre enoncé juste au dessus : name, url, type

2023-03-08 16:13 UTC, clemzarch commented on content/core-concept/satellite/_index.en.md
> +The `auth` parameter is optional and allows you to use registries that are not public and accessed through an authentication.
```suggestion
The `auth` parameter is optional and allows you to use registries that are not public, and must be accessed through an authentication.
```

2023-03-08 16:13 UTC, clemzarch commented on content/core-concept/satellite/_index.en.md
> +> Notice : Currently, the only way to identify to a repository is to use tokens. Support for other authentication methods is in our backlog.
le mettre après le block de code ?

2023-03-08 16:13 UTC, clemzarch commented on content/getting-started/environment-setup/_index.en.md
> +After installing PHP, you must ensure that your Composer 2 is installed on your machine.
```suggestion
After installing PHP, you must ensure that Composer 2 is installed on your machine.
```

2023-03-08 16:13 UTC, clemzarch commented on content/getting-started/execution/_index.en.md
> +n the following paragraphs, you will find the method for executing the satellites depending on
```suggestion
In the following paragraphs, you will find the method for executing the satellites depending on 
```

2023-03-09 13:09 UTC, sebprt commented on content/connectivity/csv/_index.en.md
>  If you want to see complete configurations, please go to the [examples](/examples) folder.
Il n'y a pas d'exemples du tout, je vais le supprimer pour l'instant. Il faudra penser à ajouter des exemples plus tard.

2023-03-09 13:19 UTC, sebprt commented on content/connectivity/csv/_index.en.md
> +    nonstandard: true
Je vais ajouter un exemple de configuration pour ce cas et pour tout le reste. Mais je ferais ça dans un deuxième temps.

2023-03-09 13:22 UTC, sebprt commented on content/core-concept/satellite/_index.en.md
> +The `require` parameter allows to add all the packages, write like `package_name:version`, that we need for your microservice.
Il faudrait utiliser le "vous" plutôt que le "nous" 

J'ai changé la phrase pour avoir

2023-03-09 13:24 UTC, sebprt commented on content/core-concept/satellite/_index.en.md
> +The `from_local` parameter is optional and copies local `composer.json`, `composer.lock` and `vendor` files in your
C'est corrigé

2023-03-09 13:24 UTC, sebprt commented on content/core-concept/satellite/_index.en.md
> +        - { name: 'private-packagist', type: 'composer', url: 'https://repo.packagist.com/package/' }
J'ai modifié l'ordre

2023-03-09 13:31 UTC, sebprt commented on content/core-concept/satellite/_index.en.md
> +The `auth` parameter is optional and allows you to use registries that are not public and accessed through an authentication.
Phrase modifiée

2023-03-09 13:31 UTC, sebprt commented on content/core-concept/satellite/_index.en.md
> +> Notice : Currently, the only way to identify to a repository is to use tokens. Support for other authentication methods is in our backlog.
C'est fait

2023-03-09 13:32 UTC, sebprt commented on content/getting-started/environment-setup/_index.en.md
> +After installing PHP, you must ensure that your Composer 2 is installed on your machine.
Modifié

2023-03-09 13:33 UTC, sebprt commented on content/getting-started/execution/_index.en.md
> +n the following paragraphs, you will find the method for executing the satellites depending on
Modifié

2023-03-16 20:15 UTC, gplanchat approved these changes

2023-03-16 20:15 UTC, merged