Documentation for plugin custom
php-etl/documentation pull request #5
Opened 2021-04-02 09:23 UTC by Thibault43

2021-04-02 09:49 UTC, sebprt commented on config.toml
> +  name = "Custom code"
Peut-être écrire "Custom" aurait suffit ?

2021-04-02 09:59 UTC, gplanchat requested changes

2021-04-02 09:59 UTC, gplanchat commented on config.toml
> +  name = "Custom code"
Renommes en "Custom connector"

2021-04-02 09:59 UTC, gplanchat commented on content/connectivity/custom/_index.en.md
> +description: "Connect your Akeneo PIM through pipelines"
Ta description n'est pas correcte

2021-04-02 09:59 UTC, gplanchat commented on content/connectivity/custom/_index.en.md
> +title: "Custom"
Renommes en "Custom connector"

2021-04-02 09:59 UTC, gplanchat commented on content/connectivity/custom/_index.en.md
> +* `loader` allows to use the data following its extraction and transformation
Ces précisions d'ordre général sont déjà faites ailleurs dans la doc, préfères utiliser un lien vers les articles appropriés dans ce cas. Tu n'expliques pas comment fonctionne une Pipeline en général, mais comment utiliser le plugin `custom` au sein d'une pipeline.

2021-04-02 09:59 UTC, gplanchat commented on content/connectivity/custom/_index.en.md
> +The custom plugin allows to extract, transform, load data either the data file format used into the Pipeline stack.
Remplaces par :

> The custom plugin allows you to use your own source code in your pipelines, allowing you to connect tools that are not supported by the standard distribution.

2021-04-02 09:59 UTC, gplanchat commented on content/connectivity/custom/_index.en.md
> +{{< /tabs >}}
Tu vas avoir un souci avec les champs `{{< tabs name="basic_definition" >}}`, l'attribut `name` doit avoir une valeur unique sur la page.

2021-04-02 09:59 UTC, gplanchat commented on content/connectivity/custom/_index.en.md
> +                  $logger: '@App\HttpKernel\Log\Logger'
Remplaces ce nom de classe de logger par `Psr\Log\LoggerInterface`

2021-04-02 09:59 UTC, gplanchat commented on content/connectivity/custom/_index.en.md
> +                  $encrypt: '@App\Security\Encrypt'
Ce service `App\Security\Encrypt` n'a pas de définition

2021-04-19 08:30 UTC, gplanchat approved these changes

2021-04-19 08:30 UTC, merged