Add a chapter on the long filter for magento plugin
php-etl/documentation pull request #65
Opened 2024-01-10 09:47 UTC by JoMessina

2024-01-10 15:38 UTC, sebprt requested changes

2024-01-10 15:38 UTC, sebprt commented on content/connectivity/magento-2/_index.en.md
> +          - '000000526,4000000026,00000918,000001754,6000000123,4000000150,6000000185,000003798,6000000211,6000000230,000004664,000004950,6000000265,6000000293,000008038,000008842,6000000475,60000004
T'aurais pu éviter de mettre autant de codes... ça fait long dans la doc et personne ne va s'amuser à lire tous les codes

2024-01-10 16:10 UTC, JoMessina commented on content/connectivity/magento-2/_index.en.md
> +          - '000000526,4000000026,00000918,000001754,6000000123,4000000150,6000000185,000003798,6000000211,6000000230,000004664,000004950,6000000265,6000000293,000008038,000008842,6000000475,60000004
C'est rectifié

2024-01-10 16:11 UTC, clemzarch approved these changes

2024-01-17 11:55 UTC, gplanchat approved these changes

2024-01-17 11:55 UTC, merged